# Numpy 실습

In [1]:
# 라이브러리 로딩
import numpy as np # numpy를 np라는 별칭(allas)을 사용해 호출

- 앞으로는 numpy에 대해서 numpy를 적지 않고 np를 통해 기능 구사할 것임

## 1-1. 파이썬 리스트에서 넘파이로 변환
- 파이썬 리스트가 넘파이와 유사하기 때문에 형태 보기

In [2]:
# 예시
a = [1, 3.14, True, 'hello'] # 리스트(정수형, 실수형, 분류형, 문자형)
b = np.array(a) # 이걸 numpy array로 바꾸면 어떻게 될까?

In [3]:
# 리스트 원소 데이터 타입 확인
print(a)
for element in a:
    print('Data type of {} : {}'.format(element, type(element)))

[1, 3.14, True, 'hello']
Data type of 1 : <class 'int'>
Data type of 3.14 : <class 'float'>
Data type of True : <class 'bool'>
Data type of hello : <class 'str'>


- a의 리스트 원소와 아래 행으로는 각 요소들을 볼 수 있다. 각각이 어떤 데이터 타입을 가지고 있는지 보고

In [4]:
# 넘파이 배열 원소 확인
print(b)
for element in b:
    print('Data type of {} : {}'.format(element, type(element)))

['1' '3.14' 'True' 'hello']
Data type of 1 : <class 'numpy.str_'>
Data type of 3.14 : <class 'numpy.str_'>
Data type of True : <class 'numpy.str_'>
Data type of hello : <class 'numpy.str_'>


- 이걸 이제 변환된 numpy 배열로 변환시키면, 어떤 원소를 갖고 있고, 원소의 타입은 어떻게 되는가 확인하자.
- 얼핏 보면 비슷하다. 그러나 모두 문자열로 치환되었다. 
- 이는 numpy가 하나의 데이터 타입만 받을 수 있기 때문이다. 그래서 string 문자열로 다 바뀌었다. 

## 1-2. 중첩 리스트를 넘파이 배열로 변환
- 이제 a를 중첩 리스트로 만들어서 확인해보겠다. 

In [5]:
# 중첩 리스트 생성
a = [[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [6]:
# 중첩리스트 데이터 타입 확인
type(a)

list

- 중첩리스트의 데이터 타입은 마찬가지로 list가 된다. 

In [7]:
# 중첩리스트를 넘파이 배열로 변환 ==> 2차원인 행렬로 변환
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]]


- 중첩리스트 같은 배열로 변하게 되었다. 이는 2차원 배열인 행렬 형태가 된다. 

In [8]:
# 행렬 데이터 타입 확인
type(b)

numpy.ndarray

- 데이터 타입을 확인해보면 numpy가 제공하는 array임을 알 수 있다. 

In [9]:
# 배열(array)의 shape 확인
b.shape # (2, 3)

(2, 3)

In [10]:
# 배열(array)의 차원 확인
b.ndim # 2

2

In [11]:
# 배열 내 총 원소 개수 확인
b.size # 6

6

In [12]:
# 2x3 행렬을 3x2로 바꿔보자
print(b.reshape(3, 2)) # 단순하게 reshape 메소드를 호출하면 된다. 

[[1 2]
 [3 4]
 [5 6]]


In [13]:
# 배열 요소 데이터타입 변경 : 정수 -> 실수
b = np.array(a, dtype=np.float64) # dtype 인수 설정
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


- 1, 2, 3, 4, 5, 6 이라는 정수를 갖고 있었다.
- 거기에 dtype라는 인수를 명시해줘서 float로 바꾸겠다 라고 명시
- 결과: 1., 2. 이런 식으로 숫자 뒤에 .이 붙는다. 이건 실수임을 의미

In [14]:
# 배열 요소 데이터타입 변경 : 실수 -> 정수 # 다른 방식으로?
b = b.astype(np.int64) # 사후 변경 시 astype 메서드로 변경 가능
print(b)

[[1 2 3]
 [4 5 6]]


## 2-1. 넘파이 배열 인덱싱

### 2-1-1. 1차원 배열 인덱싱

In [15]:
# 새로운 배열 arr 생성
arr = np.array([1, 2, 3, 4, 5])

- 1차원 배열 인덱싱은 파이썬의 list 인덱싱과 동일함
- arr(array를 뜻하는) 변수를 하나 생성한 뒤에, 그 변수는 1, 2, 3, 4, 5 numpy 배열이 된다. 

In [16]:
print(arr)

[1 2 3 4 5]


In [17]:
# 배열 첫번쨰 원소 가져오기
print(arr[0])

1


In [18]:
# 배열 네번쨰 원소 가져오기
print(arr[3])

4


In [19]:
# 배열 마지막 원소 가져오기
print(arr[-1]) # -1을 입력하면 마지막 변수 가져올 수 있음

5


### 2-1-2. 2차원 배열 인덱싱
- 2차원 이상의 배열일 경우에는 , 를 사용하여 원하는 데이터에 접근할 수 있다.
- 이 부분이 python 데이터 list와 가장 차이가 나는 부분

In [20]:
# 2차원 배열 생성
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [21]:
# 위의 형태가 익숙하지 않다면, 행렬의 모양으로 직관적으로 표현하면 도움됨
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6]])

In [22]:
# 1행 1열 원소 가져오기 --> arr[행, 열]로 명시하여 원하는 위치의 데이터에 접근 가능
arr_2d[0, 0] # 콤마를 기준으로 '행'과 '열'을 구분하는 것임

1

In [23]:
# 2행 3열 원소 가져오기
arr_2d[1, 2] # 콤마를 기준으로 두번째 행(1)과 세번쨰 열(3)의 원소에 접근 가능

6

## 3-1. 배열 슬라이싱
- numpy array의 원소 중 한 개 이상의 연속된 원소들에 접근할 때 사용
- 이때도 , 로 행과 열을 구분 가능
- 1차원 배열은 사실상 list와 비슷하므로, 생략함

### 3-1-1. 2차원 배열 슬라이싱

In [24]:
# 슬라이싱 실습에 사용할 넘파이 배열을 arange라는 넘파이 메서드를 이용해서 만들어보자
arr_2d = np.arange(1, 7).reshape(2, 3)

print(arr_2d)

[[1 2 3]
 [4 5 6]]


- arange(시작 숫자, 끝 숫자): 시작 숫자부터 끝 숫자 -1까지의 번호가 나열되어 저장됨(ex. 1, 2, 3, 4, 5, 6까지의 원소를 array에 담겠다)
- reshape(행, 열) : 원소 개수에 맞춰 reshape을 활용하면 배열의 크기를 바꿀 수 있다(ex. 1차원 배열을 2행 3열인 행렬로 변환)
- 또한 활용에 따라 차원도 변경이 가능하다는 것을 알아두자!- 

In [25]:
# 첫번째 행 전체 가져오기
print(arr_2d[0, :]) # 첫번쨰 행(0)에 대해 모든 열(:)의 값 출력

[1 2 3]


In [26]:
# 세번째 열 전체 출력
print(arr_2d[:, 2]) # 3번쨰 열(3, 6)에 있는 모든 원소 출력

[3 6]


In [27]:
# 전체 행 두번째 열까지 모두 출력
print(arr_2d[:, :2]) # :2 = 0, 1

[[1 2]
 [4 5]]


# Pandas 실습

In [28]:
# 라이브러리 로딩
import pandas as pd # pandas를 pd라는 별칭(allas)을 사용해 호출

## 1-1. 데이터 생성

In [29]:
# 예시
data = {
    '이름': ['아이유', '김연아', '홍길동', '장범준', '강감찬'],
    '학과': ['국문학', '수학', '컴퓨터', '철학', '경영학'],
    '성적': [3.0, 1.0, 3.5, 2.7, 4.0]
}

- 이 dictionary는 이름, 학과, 성적이라는 key와 그에 따른 value가 나타나 있다.

In [30]:
data

{'이름': ['아이유', '김연아', '홍길동', '장범준', '강감찬'],
 '학과': ['국문학', '수학', '컴퓨터', '철학', '경영학'],
 '성적': [3.0, 1.0, 3.5, 2.7, 4.0]}

## 1-2. 데이터 프레임으로 변환

In [31]:
# 딕셔너리 타입인 data를 pd.DataFrame() 인자로 넣어주면 된다!
df = pd.DataFrame(data) # pandas가 제공하는 DataFreme 함수를 사용해서 딕셔너리(data)를 넣어준다. 

display(df) # display 함수를 사용하면 -> 쉽고 이쁘게 출력 가능

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

## 2-1. 데이터 csv로 저장하기

In [32]:
# 현재 워킹 디렉터리 확인
import os

current_directory = os.getcwd()

print(f"현재 워킹 디렉터리: {current_directory}")

현재 워킹 디렉터리: C:\Users\user\AIBLE SCHOOL_pre


In [33]:
# 데이터프레임을 csv로 저장 --> to_csv 메소드 이용
df.to_csv('./data/student.csv', sep=',', index=False)

- .은 현재 있는 위치의 working directory를 말함
- 현재 주피터 노트북 파일이 있는 워킹 디렉토리에 data라는 폴더가 있고, 그 안에 student라는 이름으로 csv 파일을 저장하겠다
- csv는 ,로 구분되기에 sep을 , 로 해준다
- index(0, 1, 2, 3, 4....) 이게 들어가지 않도록 false 해주어야 함

## 2-2. 데이터 불러오기

In [34]:
# 데이터 로딩은 pandas의 read_csv라는 함수를 활용하면 됨
df = pd.read_csv('./data/student.csv') # 경로설정만 잘 해주면 됨
display(df)

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

## 3-1. pandas로 원하는 데이터 선택하기

## 4-1. 슬라이싱(slicing)

In [35]:
# 데이터 슬라이싱
df[1:5] # 데이터의 1번 행부터 4번 행까지

이름   학과   성적
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [36]:
df[0:3] # 첫번째부터 세번째 행까지

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5

In [37]:
df[0:] # 모든 행의 데이터에 접근

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [38]:
df[:] # 위와 동일한 카드

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [39]:
df # 그냥 이렇게 쳐도 됨

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

## 5-1. 인덱싱(indexing)
- 만약에 데이터 프레임에 대해서 인덱싱한다면 어떻게 될까?

In [44]:
# 그냥 나는 numpy처럼 두번째 행에 대한 정보를 가져오고 싶어. 
# df[1] # key error가 뜬다. 데이터 프레임엔 이런 방식으로 인덱싱할 수 없기 때문!

### 5-1-1. 단순 인덱싱(indexing)
- 만약에 데이터 프레임에 대해서 인덱싱한다면 어떻게 될까?

In [42]:
# 데이터 프레임으로 인덱싱하려면 컬럼명을 주어야 한다! 
df['이름']

0    아이유
1    김연아
2    홍길동
3    장범준
4    강감찬
Name: 이름, dtype: object

- 이름이라는 column이 있기 때문에 이름에 대해서 indexing 한다면, 이렇게 이름에 대한 series가 출력됨

In [45]:
# 마찬가지로 다른 컬럼명을 주어 단순 인덱싱
df['학과']

0    국문학
1     수학
2    컴퓨터
3     철학
4    경영학
Name: 학과, dtype: object

## 6-1. fancy indexing
- 여러 개의 컬럼을 선택하여 원하는 컬럼으로만 데이터프레임, 또는 series를 구성할 때 사용할 수 있다는 것을 실습 이론 시간에서 배웠다

In [46]:
# 인덱싱 시 리스트로 값을 주면 됨
# 이름과 학과 컬럼에만 접근하고 싶다면? 
df[['이름', '학과']] # df[리스트]

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동  컴퓨터
3  장범준   철학
4  강감찬  경영학

- 리스트로 ,를 구분지어서 주고, 데이터 프레임에 대해서 인덱싱을 해준다. 

## 7-1. [응용] 슬라이싱 + 인덱싱
- 둘을 같이 응용해서 활용해보자.
- 슬라이싱은 행에 대한 데이터를 가져오는 것임을 기억

In [47]:
df[1:3][['학과', '이름']]

학과   이름
1   수학  김연아
2  컴퓨터  홍길동

In [48]:
df[['학과', '이름']][1:3] # 순서를 바꿔도 동일하게 결과가 나타난다. 

학과   이름
1   수학  김연아
2  컴퓨터  홍길동

## 8-1. Boolean indexing
- 어떤 조건식을 세워서 True와 False로 데이터를 구분하여 True인 행에 대해서만 데이터를 불러오는 것이 특징
- 연산자를 이용하여 인덱싱 수행
- e.g. ==, !=, >, etc

In [50]:
# 수학과 소속인 학생의 데이터만 불러오자
df[df['학과'] == '수학'] # 학과라는 컬럼에 대해서 행들이 '수학'이라는 값을 가지고 있는 행만 불러오기

이름  학과   성적
1  김연아  수학  1.0

이렇듯 `df[ 불리언 리스트 ]` 로 작동하는 원리다. <br>
간단한 예시) 

| 이름 | 성적 |
| --- | --- |
| A | 100 |
| B | 80 |
| C | 70 |
| D | 95 |
| E | 90 |
| F | 20 |
| G | 50 |
| H | 55 |
| I | 94 |

해당 데이터에서 90점 이상의 점수를 받은 학생들의 데이터만 불러오고 싶다면?
`df['성적'] >= 90` 이라는 명령어 입력 --> 불리언 값(`True`/`False`) 출력
```
A   True
B   False
C   False
.   
.     
H   False
I   True
```

`df[df['성적'] >= 90]` 이라는 명령어는 `df[[True, False, False, ..., False, True]]` 이렇게 해석 가능 <br>
`True`인 행에 관한 모든 정보에 접근

In [51]:
# 성적이 0.5로 나누어 떨어지는 행에 접근
df[df['성적'] % 0.5 == 0]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
4  강감찬  경영학  4.0

In [53]:
df['성적'] % 0.5 == 0 # 세번째 행은 False라서 결과 위 데이터 행에서 사라진 것을 확인 가능!

0     True
1     True
2     True
3    False
4     True
Name: 성적, dtype: bool

## 9-1. pandas 고급 인덱싱 `loc` & `iloc` 인덱서
- 우리는 슬라이싱으로 데이터 프레임에 대해서 '행'에 관한 정보를 접근할 수 있었다.
- 하지만 인덱싱으로는 접근할 수 없었음..
- 그렇지만 loc나 iloc 인덱서를 사용한다면, 그냥 단순하게 인덱스에 대한 정보를 준다면 아래와 같이 series로 떨어지는 것을 확인 가능

### 9-1-1. 한 개의 행에 대해서만 loc indexing

In [57]:
df.loc[3]

이름    장범준
학과     철학
성적    2.7
Name: 3, dtype: object

In [59]:
# SERIES에 대한 데이터 타입 확인
# df.loc[3]에 대한 데이터 타입은?
type(df.loc[3]) # pandas.core.series.Series

pandas.core.series.Series

In [56]:
df

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

- 실제로도 데이터 프레임을 보게 되면, 인덱스 값이 3인, 장범준 학생에 대한 정보가 모조리 출력됨을 확인!

### 9-1-2. 여러 개의 행을 fancy indexing을 통해 불러오기

In [60]:
# 행에 대해서 fancy indexing
df.loc[[1, 3, 4]] # loc 인덱서에 리스트로 값을 부여

이름   학과   성적
1  김연아   수학  1.0
3  장범준   철학  2.7
4  강감찬  경영학  4.0

- 인덱스의 값을 리스트로 주어서, 부여해봤더니 인덱스 값이 1, 3, 4 값을 가진 학생 정보 불러올 수 있었다.
- 슬라이싱으로 가져오려고 했다면, 2번 인덱스 홍길동 학생 정보를 가져와야 했을 것이다..

In [61]:
# , 로 구분한다면 열에 대한 정보도 가져올 수 있다. 
# 행에 대해서 fancy indexing과 칼럼 슬라이싱
df.loc[[1, 3, 4], :]

이름   학과   성적
1  김연아   수학  1.0
3  장범준   철학  2.7
4  강감찬  경영학  4.0

- fancy indexing으로 행에 대한 정보를 입력해주고,
- 열은 모든 열에 대해서 가져오겠다.
- 동일한 결과가 도출된다. 

In [62]:
# 행에 대해서 fancy indexing과 원하는 컬럼 슬라이싱
df.loc[[1, 3, 4], '이름':'성적']

이름   학과   성적
1  김연아   수학  1.0
3  장범준   철학  2.7
4  강감찬  경영학  4.0

- 컬럼의 경우에는 loc를 주었기 때문에, 컬럼명(문자열)으로 주어야 한다

In [63]:
# 행과 열에 대해서 모두 fancy indexing 
df.loc[[1, 3, 4], ['이름', '성적']]

이름   성적
1  김연아  1.0
3  장범준  2.7
4  강감찬  4.0

### 9-1-3. 만약 loc 대신, iloc 인덱서를 사용한다면?

In [64]:
df.iloc[[1, 3, 4], 0:2] # loc는 컬럼 명을 명시 --> iloc는 컬럼의 순서를 명시

이름   학과
1  김연아   수학
3  장범준   철학
4  강감찬  경영학

### 9-1-4. loc + boolean indexing
- 이렇게 활용하면 좀 더 원하는 데이터를 가져올 수 있다. 

In [65]:
# 성적이 2로 나누어지지 않는 행에 대해서 접근 ---> 그 행에 대해서 이름, 학과, 성적 컬럼만!
df.loc[df['성적'] % 2 != 0, ['이름', '학과', '성적']]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.0
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7